{
  "id": "api/operators/catchError",
  "title": "catchError",
  "contents": "\n\n<article>\n  <div class=\"page-actions\">\n    <a href=\"https://github.com/reactivex/rxjs/edit/master/src/internal/operators/catchError.ts?message=docs(operators)%3A%20describe%20your%20change...#L13-L157\" aria-label=\"编辑建议\" title=\"编辑建议\"><i class=\"material-icons\" aria-hidden=\"true\" role=\"img\">mode_edit</i></a>\n    <a href=\"https://github.com/reactivex/rxjs/tree/8.0.0-alpha.7/src/internal/operators/catchError.ts#L13-L157\" aria-label=\"查看源码\" title=\"查看源码\"><i class=\"material-icons\" aria-hidden=\"true\" role=\"img\">code</i></a>\n  </div>\n    <div class=\"breadcrumb\">\n      <script type=\"application/ld+json\">\n        {\n          \"@context\": \"http://schema.org\",\n          \"@type\": \"BreadcrumbList\",\n          \"itemListElement\": [\n          { \"@type\": \"ListItem\", \"position\": 1, \"item\": { \"@id\": \"https://angular.io//api\", \"name\": \"API\" } },\n          { \"@type\": \"ListItem\", \"position\": 2, \"item\": { \"@id\": \"https://angular.io/api/operators\", \"name\": \"rxjs/operators\" } },\n          { \"@type\": \"ListItem\", \"position\": 3, \"item\": { \"@id\": \"https://angular.io/api/operators/catchError\", \"name\": \"catchError\" } }\n          ]\n        }\n      </script>\n      <a href=\"/api\">API</a> / <a href=\"api/operators\">rxjs/operators</a>\n    </div>\n  <header class=\"api-header\">\n    <h1 id=\"catcherror\">catchError<a title=\"Link to this heading\" class=\"header-link\" aria-hidden=\"true\" href=\"api/operators/catchError#catcherror\"><i class=\"material-icons\">link</i></a></h1>\n    <label class=\"api-type-label function\">function</label>\n    \n    \n    <label class=\"api-status-label stable\">稳定</label>\n    \n    <label class=\"api-status-label operator\">操作符</label>\n  </header>\n  <aio-toc class=\"embedded\"></aio-toc>\n\n  <div class=\"api-body\">\n    \n  \n\n  <p class=\"short-description\"></p><p>Catches errors on the observable to be handled by returning a new observable or throwing an error.</p>\n<p>捕获要处理的 observable 上的错误，并返回新的 observable 或抛出错误。</p>\n<p></p>\n  \n\n  \n\n  \n\n  <code-example language=\"ts\" hidecopy=\"true\" class=\"no-box api-heading\"> <a href=\"api/index/function/catchError\" class=\"code-anchor\">catchError</a>&#x3C;T, O extends <a href=\"api/index/type-alias/ObservableInput\" class=\"code-anchor\">ObservableInput</a>&#x3C;any>>(selector: (err: any, caught: <a href=\"api/index/class/Observable\" class=\"code-anchor\">Observable</a>&#x3C;T>) => O): <a href=\"api/index/interface/OperatorFunction\" class=\"code-anchor\">OperatorFunction</a>&#x3C;T, T | <a href=\"api/index/type-alias/ObservedValueOf\" class=\"code-anchor\">ObservedValueOf</a>&#x3C;O>></code-example>\n\n\n\n  <h4 class=\"no-anchor\" id=\"parameters\">参数</h4>\n  <table class=\"is-full-width list-table parameters-table function-overload-parameters\">\n  <tbody>\n  \n    <tr class=\"function-overload-parameter\">\n      <td class=\"param-name\">\n        <a id=\"selector\"></a>\n        <code>selector</code>\n      </td>\n      <td class=\"param-type\"><code>(err: any, caught: <a href=\"api/index/class/Observable\" class=\"code-anchor\">Observable</a>&#x3C;T>) => O</code></td>\n      <td class=\"param-description\">\n      <p>        a function that takes as arguments <code>err</code>, which is the error, and <code>caught</code>, which\nis the source observable, in case you'd like to \"retry\" that observable by returning it again. Whatever observable\nis returned by the <code>selector</code> will be used to continue the observable chain.</p>\n<p>一个函数，它的第一个参数是 <code>err</code>，这是错误对象，第二个参数是 <code>caught</code>，这是源 observable，这样你就可以再次返回它来“重试”那个 observable。<code>selector</code> 返回的任何 observable 都将用作后续 observable 链。</p>\n\n      </td>\n    </tr>\n  </tbody>\n</table>\n\n  \n  <h4 class=\"no-anchor\" id=\"返回值\">返回值</h4>\n  <p><code><a href=\"api/index/interface/OperatorFunction\" class=\"code-anchor\">OperatorFunction</a>&#x3C;T, T | <a href=\"api/index/type-alias/ObservedValueOf\" class=\"code-anchor\">ObservedValueOf</a>&#x3C;O>></code>: A function that returns an Observable that originates from either\nthe source or the Observable returned by the <code>selector</code> function.</p>\n<p>一个返回 Observable 的函数，该 Observable 或者来自源或者来自 <code>selector</code> 函数返回的 Observable。</p>\n\n  \n\n\n\n\n\n\n\n  \n\n<section class=\"description\">\n  <h2 id=\"description\">说明<a title=\"Link to this heading\" class=\"header-link\" aria-hidden=\"true\" href=\"api/operators/catchError#description\"><i class=\"material-icons\">link</i></a></h2>\n  <span class=\"informal\">\nIt only listens to the error channel and ignores notifications.\nHandles errors from the source observable, and maps them to a new observable.\nThe error may also be rethrown, or a new error can be thrown to emit an error from the result.\n</span>\n<p><img src=\"/assets/images/marble-diagrams/catch.png\" width=\"100%\" alt=\"catch marble diagram\"></p>\n<p>This operator handles errors, but forwards along all other events to the resulting observable.\nIf the source observable terminates with an error, it will map that error to a new observable,\nsubscribe to it, and forward all of its events to the resulting observable.</p>\n<p>该操作符会处理各种错误，但会把所有其它事件转发到结果 observable。如果源 observable 因出错而终止，它会将该错误映射成新的 observable，订阅这个新 Observable，并将其所有事件转发到结果 observable。</p>\n<h2 id=\"examples\">Examples<a title=\"Link to this heading\" class=\"header-link\" aria-hidden=\"true\" href=\"api/operators/catchError#examples\"><i class=\"material-icons\">link</i></a></h2>\n<h2 id=\"例子\">例子<a title=\"Link to this heading\" class=\"header-link\" aria-hidden=\"true\" href=\"api/operators/catchError#例子\"><i class=\"material-icons\">link</i></a></h2>\n<p>Continue with a different Observable when there's an error</p>\n<p>出现错误时继续使用另一个 Observable</p>\n<code-example language=\"ts\">\nimport { <a href=\"api/index/function/of\" class=\"code-anchor\">of</a>, <a href=\"api/index/function/map\" class=\"code-anchor\">map</a>, <a href=\"api/index/function/catchError\" class=\"code-anchor\">catchError</a> } from 'rxjs';\n\n<a href=\"api/index/function/of\" class=\"code-anchor\">of</a>(1, 2, 3, 4, 5)\n  .pipe(\n    <a href=\"api/index/function/map\" class=\"code-anchor\">map</a>(n => {\n      if (n === 4) {\n        throw 'four!';\n      }\n      return n;\n    }),\n    <a href=\"api/index/function/catchError\" class=\"code-anchor\">catchError</a>(err => <a href=\"api/index/function/of\" class=\"code-anchor\">of</a>('I', 'II', 'III', 'IV', 'V'))\n  )\n  .subscribe(x => console.log(x));\n  // 1, 2, 3, I, II, III, IV, V\n</code-example>\n<p>Retry the caught source Observable again in case of error, similar to <code><a href=\"api/index/function/retry\" class=\"code-anchor\">retry</a>()</code> operator</p>\n<p>发生错误时再次重试所捕获的源 Observable，类似于 <code><a href=\"api/index/function/retry\" class=\"code-anchor\">retry</a>()</code> 操作符</p>\n<code-example language=\"ts\">\nimport { <a href=\"api/index/function/of\" class=\"code-anchor\">of</a>, <a href=\"api/index/function/map\" class=\"code-anchor\">map</a>, <a href=\"api/index/function/catchError\" class=\"code-anchor\">catchError</a>, <a href=\"api/index/function/take\" class=\"code-anchor\">take</a> } from 'rxjs';\n\n<a href=\"api/index/function/of\" class=\"code-anchor\">of</a>(1, 2, 3, 4, 5)\n  .pipe(\n    <a href=\"api/index/function/map\" class=\"code-anchor\">map</a>(n => {\n      if (n === 4) {\n        throw 'four!';\n      }\n      return n;\n    }),\n    <a href=\"api/index/function/catchError\" class=\"code-anchor\">catchError</a>((err, caught) => caught),\n    <a href=\"api/index/function/take\" class=\"code-anchor\">take</a>(30)\n  )\n  .subscribe(x => console.log(x));\n  // 1, 2, 3, 1, 2, 3, ...\n</code-example>\n<p>Throw a new error when the source Observable throws an error</p>\n<p>当源 Observable 抛出错误时抛出一个新的错误</p>\n<code-example language=\"ts\">\nimport { <a href=\"api/index/function/of\" class=\"code-anchor\">of</a>, <a href=\"api/index/function/map\" class=\"code-anchor\">map</a>, <a href=\"api/index/function/catchError\" class=\"code-anchor\">catchError</a> } from 'rxjs';\n\n<a href=\"api/index/function/of\" class=\"code-anchor\">of</a>(1, 2, 3, 4, 5)\n  .pipe(\n    <a href=\"api/index/function/map\" class=\"code-anchor\">map</a>(n => {\n      if (n === 4) {\n        throw 'four!';\n      }\n      return n;\n    }),\n    <a href=\"api/index/function/catchError\" class=\"code-anchor\">catchError</a>(err => {\n      throw 'error in source. Details: ' + err;\n    })\n  )\n  .subscribe({\n    next: x => console.log(x),\n    error: err => console.log(err)\n  });\n  // 1, 2, 3, error in source. Details: four!\n</code-example>\n\n</section>\n\n\n\n\n  \n\n  \n<section class=\"see-also\">\n  <h2 id=\"see-also\">参见<a title=\"Link to this heading\" class=\"header-link\" aria-hidden=\"true\" href=\"api/operators/catchError#see-also\"><i class=\"material-icons\">link</i></a></h2>\n  <ul>\n  \n    <li><a href=\"api/index/function/onErrorResumeNext\"><code>onErrorResumeNext</code></a>\n</li>\n    <li><a href=\"api/operators/repeat\"><code>repeat</code></a>\n</li>\n    <li><a href=\"api/operators/repeatWhen\"><code>repeatWhen</code></a>\n</li>\n    <li><a href=\"api/operators/retry\"><code>retry</code></a>\n</li>\n    <li><a href=\"api/operators/retryWhen\"><code>retryWhen</code></a>\n</li>\n  </ul>\n</section>\n\n\n\n  </div>\n</article>\n\n<!-- links to this doc:\n - api/operators\n - api/operators/timeout\n-->\n<!-- links from this doc:\n - /api\n - api/index/class/Observable\n - api/index/function/catchError\n - api/index/function/map\n - api/index/function/of\n - api/index/function/onErrorResumeNext\n - api/index/function/retry\n - api/index/function/take\n - api/index/interface/OperatorFunction\n - api/index/type-alias/ObservableInput\n - api/index/type-alias/ObservedValueOf\n - api/operators\n - api/operators/catchError#catcherror\n - api/operators/catchError#description\n - api/operators/catchError#examples\n - api/operators/catchError#see-also\n - api/operators/catchError#例子\n - api/operators/repeat\n - api/operators/repeatWhen\n - api/operators/retry\n - api/operators/retryWhen\n - https://github.com/reactivex/rxjs/edit/master/src/internal/operators/catchError.ts?message=docs(operators)%3A%20describe%20your%20change...#L13-L157\n - https://github.com/reactivex/rxjs/tree/8.0.0-alpha.7/src/internal/operators/catchError.ts#L13-L157\n-->"
}